### ISSUE TITLE
PRESENCE_UPDATE needs updating after sponge/forge update.

### ISSUE THREAD

**Issue by ProsperCraft** [nguyenquyhy/Sponge-Discord#25]
I just updated Sponge and forge for 1.10.2 and I am seeing this stacktrace in console.

[08:58:51] [pool-11-thread-1/WARN] [de.btobastian.javacord.utils.PacketHandler]: Couldn't handle packet of type PRESENCE_UPDATE. Please contact the developer! (packet: {"nick":null,"game":null,"roles":[],"guild_id":"99958278427017216","user":{"id":"229634027097817089"},"status":"offline"})
org.json.JSONException: JSONObject["username"] not found.
        at org.json.JSONObject.get(JSONObject.java:473) ~[JSONObject.class:?]
        at org.json.JSONObject.getString(JSONObject.java:654) ~[JSONObject.class:?]
        at de.btobastian.javacord.entities.impl.ImplUser.<init>(ImplUser.java:89) ~[ImplUser.class:?]
        at de.btobastian.javacord.ImplDiscordAPI.getOrCreateUser(ImplDiscordAPI.java:968) ~[ImplDiscordAPI.class:?]
        at de.btobastian.javacord.utils.handler.user.PresenceUpdateHandler.handle(PresenceUpdateHandler.java:60) ~[PresenceUpdateHandler.class:?]
        at de.btobastian.javacord.utils.PacketHandler$1.run(PacketHandler.java:71) [PacketHandler$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by VankkaGithub** [comment]
Looks like a issue with Javacord but i could be wrong

**Comment by nguyenquyhy** [comment]
This is fixed in 2.2.0, which will be released soon.
