### ISSUE TITLE
error

### ISSUE THREAD

**Issue by CraftYourWay** [nguyenquyhy/Sponge-Discord#7]
[23:50:58] [Server thread/ERROR] [Sponge]: Could not pass GameStartedServerEvent$Impl to Plugin{id=com.nguyenquyhy.spongediscord, name=Sponge Discord, version=1.2.0, source=mods/Sponge-Discord-1.2.1-all.jar}
java.lang.NullPointerException
	at com.nguyenquyhy.spongediscord.SpongeDiscord.onServerStart(SpongeDiscord.java:165) ~[SpongeDiscord.class:?]
	at org.spongepowered.common.event.listener.GameStartedServerEventListener_SpongeDiscord_onServerStart8.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-5.0.0-BETA-94]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:287) [SpongeEventManager.class:1.10.2-5.0.0-BETA-94]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:300) [SpongeEventManager.class:1.10.2-5.0.0-BETA-94]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:304) [SpongeEventManager.class:1.10.2-5.0.0-BETA-94]
	at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:194) [SpongeImpl.class:1.10.2-5.0.0-BETA-94]
	at org.spongepowered.server.SpongeVanilla.onServerStarting(SpongeVanilla.java:217) [SpongeVanilla.class:1.10.2-5.0.0-BETA-94]
	at net.minecraft.server.dedicated.DedicatedServer.handler$callServerStarting$0(SourceFile:85) [ld.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:228) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:428) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by nguyenquyhy** [comment]
Please try again with the latest release.
