### ISSUE TITLE
[1.12] Can't Find Channel

### ISSUE THREAD

**Issue by TooVeryIcey** [nguyenquyhy/Sponge-Discord#73]
Hello,
It seems that my version of the plugin cannot find the channel, And to top it off, has never even tried to join my discord, if that is something I need to do manually please let me know how...As said in the title I am running my server SPongeVanilla 1.12 Latest Release And the latest version of DiscordBridge!
My [Plugins Are](https://hastebin.com/imogozuren.pas)
My [Config Is](https://hastebin.com/muzotoburu.json)
My [Discord Setup Is](https://gyazo.com/93cc3bc7c35342df28139c14e85c80d1)
The [Erros Is](https://hastebin.com/ayiwegawab.md)

**Comment by LJack2k** [comment]
This also happens with 1.10. I think Discord made some API changes.

**Comment by Mohron** [comment]
You have to manually invite your bot to your server and make sure it has the permissions it needs to use the channel you specified in the config.

**Comment by LJack2k** [comment]
That is already done.

Op 14 sep. 2017 20:12 schreef "Mohron" <notifications@github.com>:

**Comment by Mohron** [comment]
Well, there are no issues with the version of the Discord API being used by this plugin.  I'm using it on multiple 1.10.2 and 1.12.1 SpongeForge servers with no issues.

**Comment by BlobCodes** [comment]
I have the same problem, the Bot has Administrator Permissions

LOG:
`[17:44:37 WARN] [PacketHandler]: Couldn't handle packet of type GUILD_CREATE. Please contact the developer! (packet: {"default_message_notifications":0,"unavailable":false,"owner_id":"96967924798992384","roles":[{"color":0,"permissions":104324161,"managed":false,"name":"@everyone","mentionable":false,"position":0,"id":"360815528945647616","hoist":false},{"color":0,"permissions":2146958591,"managed":true,"name":"CatBot","mentionable":false,"position":1,"id":"360816188256681994","hoist":false},{"color":0,"permissions":2146958591,"managed":false,"name":"OP","mentionable":true,"position":1,"id":"360816368230203393","hoist":false},{"color":0,"permissions":8,"managed":true,"name":"BlobBot","mentionable":false,"position":1,"id":"361148050858835968","hoist":false},{"color":0,"permissions":8,"managed":true,"name":"Rythm","mentionable":false,"position":1,"id":"361187436857917450","hoist":false},{"color":0,"permissions":40,"managed":true,"name":"himebot","mentionable":false,"position":1,"id":"361190682796359680","hoist":false},{"color":0,"permissions":8,"managed":true,"name":"Gnar-bot","mentionable":false,"position":1,"id":"361192402821578763","hoist":false},{"color":0,"permissions":2146958591,"managed":true,"name":"Chilln'","mentionable":false,"position":1,"id":"361193652841873438","hoist":false},{"color":0,"permissions":2146958591,"managed":true,"name":"Sheepbot","mentionable":false,"position":1,"id":"361194458705821697","hoist":false}],"icon":"32a45a2abcaaa4191bc50207a5a0ea45","system_channel_id":"360815528945647620","afk_timeout":300,"features":[],"presences":[{"game":null,"user":{"id":"96967924798992384"},"status":"online"},{"game":{"name":"Say ;;help","type":0},"user":{"id":"184405311681986560"},"status":"online"},{"game":{"name":"_help | 29","type":0},"user":{"id":"201503408652419073"},"status":"online"},{"game":{"name":".help | .invite","type":0},"user":{"id":"232916519594491906"},"status":"online"},{"game":null,"user":{"id":"235088799074484224"},"status":"online"},{"game":{"name":"Type !!help","type":0},"user":{"id":"244423082045997057"},"status":"online"},{"game":null,"user":{"id":"315435020494045184"},"status":"online"},{"game":{"name":"Garry's Mod","type":0},"user":{"id":"360448931148070923"},"status":"online"}],"afk_channel_id":null,"members":[{"joined_at":"2017-09-22T15:52:05.798000+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"96967924798992384","avatar":"fbe3b94ae3db0e099890075f9dbe2cab","username":"BlobCodes","discriminator":"3549"}},{"joined_at":"2017-09-22T15:53:08.954000+00:00","roles":["360816368230203393"],"deaf":false,"mute":false,"user":{"id":"117910095580495874","avatar":null,"username":"Vorlonambassador","discriminator":"5973"}},{"joined_at":"2017-09-23T16:45:42.503822+00:00","roles":[],"deaf":false,"mute":false,"user":{"bot":true,"id":"184405311681986560","avatar":"f20c8d9639cd674652254af0ffd3e9d2","username":"FredBoat♪♪","discriminator":"7284"}},{"nick":null,"joined_at":"2017-09-23T16:49:39.450864+00:00","roles":["361192402821578763"],"deaf":false,"mute":false,"user":{"bot":true,"id":"201503408652419073","avatar":"09572b4d279cbfc3fcc4a993782bf1b4","username":"Gnar","discriminator":"8315"}},{"nick":null,"joined_at":"2017-09-23T16:42:49.359438+00:00","roles":["361190682796359680"],"deaf":false,"mute":false,"user":{"bot":true,"id":"232916519594491906","avatar":"0f3d15b6d41ff2ffdbe9e4051a04503f","username":"hime hime","discriminator":"3590"}},{"nick":null,"joined_at":"2017-09-23T16:29:55.465281+00:00","roles":["361187436857917450"],"deaf":false,"mute":false,"user":{"bot":true,"id":"235088799074484224","avatar":"8917d25c11a6c155a81d54640c6fd35a","username":"Rythm","discriminator":"3722"}},{"nick":null,"joined_at":"2017-09-23T16:57:49.653590+00:00","roles":["361194458705821697"],"deaf":false,"mute":false,"user":{"bot":true,"id":"244423082045997057","avatar":"85a047fa226b6fc8e6687dbe522eb432","username":"Sheepbot","discriminator":"2537"}},{"nick":null,"joined_at":"2017-09-23T16:54:37.486326+00:00","roles":["361193652841873438"],"deaf":false,"mute":false,"user":{"bot":true,"id":"296995285421391872","avatar":"1811e4524c5a075ce6c49f64a2526af8","username":"Chilln'","discriminator":"1126"}},{"nick":null,"joined_at":"2017-09-23T13:53:25.120709+00:00","roles":["361148050858835968"],"deaf":false,"mute":false,"user":{"bot":true,"id":"315435020494045184","avatar":"503e3e2437315e49ba1376b78892cb53","username":"BlobBot","discriminator":"9570"}},{"joined_at":"2017-09-23T16:55:55.217828+00:00","roles":[],"deaf":false,"mute":false,"user":{"bot":true,"id":"341898002064998402","avatar":"ac4b954618e1b3eab4c492551fc5f2ac","username":"Saxo_Broko Music","discriminator":"2329"}},{"joined_at":"2017-09-22T15:58:25.894000+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"360448931148070923","avatar":null,"username":"TROD","discriminator":"4823"}},{"joined_at":"2017-09-23T13:51:12.060743+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"360811804319809537","avatar":null,"username":"VorlonAmbassador","discriminator":"1241"}},{"joined_at":"2017-09-22T15:54:42.914000+00:00","roles":["360816188256681994"],"deaf":false,"mute":false,"user":{"bot":true,"id":"360813032428929037","avatar":null,"username":"CatBot","discriminator":"2289"}},{"joined_at":"2017-09-23T14:18:59.670076+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"361153989921734657","avatar":null,"username":"Davidkel","discriminator":"0648"}}],"voice_states":[],"id":"360815528945647616","member_count":14,"emojis":[],"large":false,"application_id":null,"joined_at":"2017-09-23T13:53:25.120709+00:00","verification_level":0,"explicit_content_filter":0,"channels":[{"permission_overwrites":[],"name":"Text Channels","bitrate":64000,"position":0,"id":"360815528945647619","user_limit":0,"type":4},{"is_private":false,"permission_overwrites":[],"last_message_id":"362238125013204993","last_pin_timestamp":"2017-09-23T14:36:25.014188+00:00","parent_id":"360815528945647619","name":"general","topic":null,"position":0,"id":"360815528945647620","type":"text"},{"permission_overwrites":[],"name":"Voice Channels","bitrate":64000,"position":0,"id":"360815528945647621","user_limit":0,"type":4},{"is_private":false,"permission_overwrites":[],"parent_id":"360815528945647621","name":"General","bitrate":64000,"position":0,"id":"360815528945647622","user_limit":0,"type":"voice"},{"is_private":false,"permission_overwrites":[{"allow":0,"deny":805829713,"id":"360815528945647616","type":"role"},{"allow":0,"deny":0,"id":"96967924798992384","type":"member"}],"last_message_id":"361486914886434817","nsfw":false,"parent_id":"360815528945647619","name":"privat","topic":null,"position":1,"id":"361086312368963584","type":"text"}],"name":"SPIELEN (TROD/VORLO)","mfa_level":0,"region":"eu-west","splash":null})
org.json.JSONException: JSONObject["type"] not a string.
        at org.json.JSONObject.getString(JSONObject.java:658) ~[JSONObject.class:?]
        at de.btobastian.javacord.entities.impl.ImplServer.<init>(ImplServer.java:111) ~[ImplServer.class:?]
        at de.btobastian.javacord.utils.handler.server.GuildCreateHandler.handle(GuildCreateHandler.java:59) ~[GuildCreateHandler.class:?]
        at de.btobastian.javacord.utils.PacketHandler$1.run(PacketHandler.java:71) [PacketHandler$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[17:44:37 WARN] [PacketHandler]: Couldn't handle packet of type GUILD_CREATE. Please contact the developer! (packet: {"default_message_notifications":1,"unavailable":false,"owner_id":"96967924798992384","roles":[{"color":0,"permissions":104324161,"managed":false,"name":"@everyone","mentionable":false,"position":0,"id":"362992013366394880","hoist":false},{"color":3066993,"permissions":8,"managed":true,"name":"BlobBot","mentionable":true,"position":7,"id":"362999078956695552","hoist":true},{"color":13897230,"permissions":267910339,"managed":false,"name":"Admin","mentionable":true,"position":8,"id":"362999332535926785","hoist":true},{"color":10354853,"permissions":104324169,"managed":false,"name":"Owner","mentionable":true,"position":9,"id":"362999391725944846","hoist":true},{"color":8832256,"permissions":133692611,"managed":false,"name":"Supporter","mentionable":true,"position":5,"id":"362999554913730571","hoist":true},{"color":9264924,"permissions":104324161,"managed":false,"name":"Builder","mentionable":true,"position":3,"id":"362999583321620481","hoist":true},{"color":3447003,"permissions":133692611,"managed":false,"name":"Developer","mentionable":true,"position":4,"id":"362999659981045763","hoist":true},{"color":1146986,"permissions":133684423,"managed":false,"name":"Moderator","mentionable":true,"position":6,"id":"362999780479205377","hoist":true},{"color":11019557,"permissions":104324161,"managed":false,"name":"YouTuber","mentionable":true,"position":1,"id":"362999864973459456","hoist":true},{"color":16761429,"permissions":104324161,"managed":false,"name":"Berühmtheit","mentionable":true,"position":2,"id":"363000498418352130","hoist":true}],"icon":null,"system_channel_id":"362998021715263488","afk_timeout":900,"features":[],"presences":[{"game":null,"user":{"id":"96967924798992384"},"status":"online"},{"game":null,"user":{"id":"315435020494045184"},"status":"online"}],"afk_channel_id":"362996477837967363","members":[{"joined_at":"2017-09-28T16:00:40.054000+00:00","roles":["362999391725944846"],"deaf":false,"mute":false,"user":{"id":"96967924798992384","avatar":"fbe3b94ae3db0e099890075f9dbe2cab","username":"BlobCodes","discriminator":"3549"}},{"joined_at":"2017-09-28T16:28:44.614000+00:00","roles":["362999078956695552"],"deaf":false,"mute":false,"user":{"bot":true,"id":"315435020494045184","avatar":"503e3e2437315e49ba1376b78892cb53","username":"BlobBot","discriminator":"9570"}}],"voice_states":[],"id":"362992013366394880","member_count":2,"emojis":[],"large":false,"application_id":null,"joined_at":"2017-09-28T16:28:44.614000+00:00","verification_level":0,"explicit_content_filter":0,"channels":[{"permission_overwrites":[],"name":"Sonstiges","bitrate":64000,"position":4,"id":"362992144874733569","user_limit":0,"type":4},{"permission_overwrites":[],"name":"Server Chats","bitrate":64000,"position":3,"id":"362992957735043073","user_limit":0,"type":4},{"permission_overwrites":[],"name":"Support","bitrate":64000,"position":2,"id":"362993155437756416","user_limit":0,"type":4},{"permission_overwrites":[],"name":"Wichtige Informationen","bitrate":64000,"position":0,"id":"362993403035648002","user_limit":0,"type":4},{"is_private":false,"permission_overwrites":[],"last_message_id":"363031366704824320","parent_id":"362993403035648002","name":"regeln","topic":null,"position":0,"id":"362993435155890176","type":"text"},{"is_private":false,"permission_overwrites":[],"last_message_id":null,"parent_id":"362993403035648002","name":"faq","topic":null,"position":1,"id":"362993487844605952","type":"text"},{"is_private":false,"permission_overwrites":[],"last_message_id":null,"parent_id":"362993403035648002","name":"ansagen","topic":null,"position":2,"id":"362993528890195968","type":"text"},{"permission_overwrites":[],"name":"Diskussionen","bitrate":64000,"position":1,"id":"362994580687421442","user_limit":0,"type":4},{"is_private":false,"permission_overwrites":[],"last_message_id":null,"parent_id":"362994580687421442","name":"general","topic":null,"position":4,"id":"362994634349215754","type":"text"},{"is_private":false,"permission_overwrites":[],"last_message_id":null,"parent_id":"362994580687421442","name":"serverteam","topic":null,"position":5,"id":"362994800116629504","type":"text"},{"is_private":false,"permission_overwrites":[],"last_message_id":null,"parent_id":"362994580687421442","name":"admins","topic":null,"position":6,"id":"362994815987875840","type":"text"},{"is_private":false,"permission_overwrites":[],"last_message_id":null,"parent_id":"362993155437756416","name":"technischer-hilfechat","topic":null,"position":9,"id":"362995636897054720","type":"text"},{"is_private":false,"permission_overwrites":[],"parent_id":"362993155437756416","name":"Support-Annahme","bitrate":64000,"position":0,"id":"362995827259736075","user_limit":0,"type":"voice"},{"is_private":false,"permission_overwrites":[],"last_message_id":null,"parent_id":"362993155437756416","name":"ingame-hilfechat","topic":null,"position":8,"id":"362996086513598467","type":"text"},{"is_private":false,"permission_overwrites":[{"allow":0,"deny":1048576,"id":"362992013366394880","type":"role"}],"parent_id":"362993155437756416","name":"Support-1","bitrate":64000,"position":1,"id":"362996144923738122","user_limit":0,"type":"voice"},{"is_private":false,"permission_overwrites":[{"allow":0,"deny":1048576,"id":"362992013366394880","type":"role"}],"parent_id":"362993155437756416","name":"Support-2","bitrate":64000,"position":2,"id":"362996226121138188","user_limit":0,"type":"voice"},{"is_private":false,"permission_overwrites":[{"allow":0,"deny":1048576,"id":"362992013366394880","type":"role"}],"parent_id":"362993155437756416","name":"Support-3","bitrate":64000,"position":3,"id":"362996258463547404","user_limit":0,"type":"voice"},{"is_private":false,"permission_overwrites":[],"parent_id":"362992144874733569","name":"Musikbot","bitrate":64000,"position":4,"id":"362996413057073152","user_limit":0,"type":"voice"},{"is_private":false,"permission_overwrites":[],"last_message_id":"363009751652499476","parent_id":"362992144874733569","name":"blobbot","topic":null,"position":10,"id":"362996447378931713","type":"text"},{"is_private":false,"permission_overwrites":[],"parent_id":"362992144874733569","name":"afk","bitrate":64000,"position":5,"id":"362996477837967363","user_limit":0,"type":"voice"},{"is_private":false,"permission_overwrites":[],"last_message_id":"362999078985924608","parent_id":"362994580687421442","name":"welcome","topic":null,"position":3,"id":"362998021715263488","type":"text"},{"is_private":false,"permission_overwrites":[{"allow":0,"deny":0,"id":"362992013366394880","type":"role"}],"last_message_id":"363348168097660929","nsfw":false,"parent_id":"362992957735043073","name":"lobby","topic":null,"position":11,"id":"363004032454754307","type":"text"}],"name":"Server","mfa_level":0,"region":"eu-west","splash":null})
org.json.JSONException: JSONObject["type"] not a string.
        at org.json.JSONObject.getString(JSONObject.java:658) ~[JSONObject.class:?]
        at de.btobastian.javacord.entities.impl.ImplServer.<init>(ImplServer.java:111) ~[ImplServer.class:?]
        at de.btobastian.javacord.utils.handler.server.GuildCreateHandler.handle(GuildCreateHandler.java:59) ~[GuildCreateHandler.class:?]
        at de.btobastian.javacord.utils.PacketHandler$1.run(PacketHandler.java:71) [PacketHandler$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[17:44:41 INFO] [discordbridge]: Bot account BlobBot will be used for all unauthenticated users!
[17:44:41 ERROR] [discordbridge]: Channel ID 362994634349215754 cannot be found! Please make sure the channel ID is correct and the bot has read & write permission for the channel.
`
